### ISSUE TITLE
As a user, I want to be able to view the Consider the Following homepage

### ISSUE THREAD

**Issue by jgarciarbridgephase** [BridgePhase/ctf#1]
# Acceptance Criteria
- Upon entering the url for the CTF application, the system shall display a homepage with the CTF logo.
- The homepage shall include the following:
    - ~~A section (carousel) for headlines~~
    - A link to a **Foods** section
    - A link to a **Prescriptions** section
    - A link to a **Medical Devices** section
    - A link to the Github repository 
    - A link to an **About Us** page
    - A link to an **About this Project** page

**Assumption**: this does not include linking to real data, just prototyping the look-and-feel of the homepage.

**Comment by jgarciarbridgephase** [comment]
The carousel portion of this story will be looked at when we integrate data. For now it's a single headline.

**Comment by belyea** [comment]
@jgarciarbridgephase  - can we make the description columns on the homepage under the icons a bit shorter? On my IE11 they come close to running into each other (looks fine on Chrome)

**Comment by jgarciarbridgephase** [comment]
@belyea can you add a screenshot? Don't have a windows machine nearby :)

**Comment by belyea** [comment]
@jgarciarbridgephase 
Here is chrome: 
![chrome images - homepage](https://cloud.githubusercontent.com/assets/11012844/8272456/2428b93a-1811-11e5-9c79-27f30f5e67c8.JPG)

Here is IE:
![ie images - homepage](https://cloud.githubusercontent.com/assets/11012844/8272458/29613ee0-1811-11e5-8144-1514229d9edb.JPG)

**Comment by jgarciarbridgephase** [comment]
@belyea - sure we can make them smaller, but I kind of wanted them to be able to wrap themselves. What I do see is if they are to wrap I should increase the padding between the columns so they don't appear to "bleed" into each other. Sort of like this: 

![screen shot 2015-06-21 at 12 31 03 pm](https://cloud.githubusercontent.com/assets/12414982/8272466/6e8e2726-1811-11e5-86e4-fd24e96c05ec.png)

**Comment by belyea** [comment]
@jgarciarbridgephase Perfect. I dont think text needs to be smaller, a little more padding would be great. Things looking really good so far!!!
