### ISSUE TITLE
As a developer, I want to deploy an initial template for the CTF application

### ISSUE THREAD

**Issue by jgarciarbridgephase** [BridgePhase/ctf#10]
# Acceptance Criteria
- The CTF application must be able to be automatically deployed on every push to `master`
  - The deployment shall utilize an automated build tool - Gradle
  - The deployment shall utilize an open-source CI pipeline - Travis CI
  - The deployment shall utilize a cloud-based IaaS/PaaS environment - Amazon AWS
  - The deployment shall utilize continuous monitoring - Amazon AWS (EC2 provides monitoring)
  - The deployment shall utilize configuration management - Github (branching and releases) and Travis CI
- The CTF application will be able to be browsed using a public DNS name

**Comment by belyea** [comment]
292BUILD SUCCESSFUL

293

294Total time: 17.721 secs
