### ISSUE TITLE
As a user I want the UI to be able to view details about food recalls

### ISSUE THREAD

**Issue by jgarciarbridgephase** [BridgePhase/ctf#2]
# Acceptance Criteria
- The system shall provide a link to view details about food recalls
- Upon clicking the link, the system shall display a summary of the most recent food recalls
- The summary shall include:
    - A table displaying the latest food recalls including information of the recall start date, reason for the recall and a product description
    - A display of US states affected by the recall
    - Contact information for the company that issued the recall

**Assumption**: this does not include linking to real data, just prototyping the look-and-feel of the food recalls section.

**Comment by jgarciarbridgephase** [comment]
@kgyovai , what do you think of displaying the latest recalls based on the state that you live in?

**Comment by jaime-garcia** [comment]
Adding a comment to make sure non-team members can add comments to issues

**Comment by eborukhov** [comment]
When I access the food page, I am unable to click on a state. Only after I select a state from the dropdown am I able to click a state on a map.
