### ISSUE TITLE
As a user, I want to view the latest food recalls in my state

### ISSUE THREAD

**Issue by jgarciarbridgephase** [BridgePhase/ctf#23]
- The recalls should be all ongoing recalls that affect my state within the last 6 months.

**Comment by belyea** [comment]
When you first go to the "Food" page, the map highlights the state, but clicking it doesn't update the dropdown. Virigina remains highlighted. However, once you use the dropdown to select a state, the new state is highlighted and then after that, the map works as designed.

**Comment by belyea** [comment]
Would it make sense to have hyperlinks (food, medicine, devices) on the banner within one of the non-home pages? Maybe the minimized images for those items in the right hand corner of the banner?

**Comment by jgarciarbridgephase** [comment]
@belyea  That sounds like a good idea, I'll prototype it and see how it goes. As for the map stuff, that's now resolved. I just finished testing with some real data.

**Comment by belyea** [comment]
@jgarciarbridgephase

**Comment by belyea** [comment]
@jgarciarbridgephase - here is a screenshot of map in chrome. Looks ok to me but map is much bigger than in IE
![bigmap](https://cloud.githubusercontent.com/assets/11012844/8272437/940e9630-1810-11e5-9dc1-c46e929e2a8d.PNG)

**Comment by belyea** [comment]
here in IE
![ie map](https://cloud.githubusercontent.com/assets/11012844/8272449/03c1d046-1811-11e5-80a4-1c70274c3b83.JPG)

**Comment by jgarciarbridgephase** [comment]
Wow that is a big difference.. ok I'll probably take a look at this tomorrow when I have access to the BridgePhase laptop in the office. The intended design is the bigger map, odd how the other map sizes properly.
