### ISSUE TITLE
Map isn't clickable when accessing from the homepage

### ISSUE THREAD

**Issue by eborukhov** [BridgePhase/ctf#27]
It becomes clickable only after I refresh the page or select a different value from the dropdown.

**Comment by jgarciarbridgephase** [comment]
ok, I fixed the clickable problem.

**Comment by jgarciarbridgephase** [comment]
Confirmed working on Production.

**Comment by jgarciarbridgephase** [comment]
@eborukhov can you please confirm as well?

http://bp-testdeployslb-1690116647.us-east-1.elb.amazonaws.com/ctf/#/home

**Comment by eborukhov** [comment]
Confirmed
