### ISSUE TITLE
Michigan is never clickable

### ISSUE THREAD

**Issue by eborukhov** [BridgePhase/ctf#29]

**Comment by jgarciarbridgephase** [comment]
Thanks, working on this now

**Comment by jgarciarbridgephase** [comment]
Michigan is now clickable!

![screen shot 2015-06-22 at 6 21 29 pm](https://cloud.githubusercontent.com/assets/12414982/8294598/8a8a3d3e-190b-11e5-8e5a-89d9489b105d.png)
