### ISSUE TITLE
Font and images look pixelated when viewing site in Firefox (V38)

### ISSUE THREAD

**Issue by echan-bridgephase** [BridgePhase/ctf#30]
![imagepixelated_firefox](https://cloud.githubusercontent.com/assets/13000338/8283054/d5cc7012-18c2-11e5-9169-5a90b6f13b39.jpg)
Font and images look pixelated when viewing site in Firefox (V38).

**Comment by jgarciarbridgephase** [comment]
Ok, it's not a bug, you're running it off a remote desktop session that doesn't have font-smoothing turned on. 
![screen shot 2015-06-22 at 9 45 33 am](https://cloud.githubusercontent.com/assets/12414982/8283157/7948fb34-18c3-11e5-996d-abd278dab80d.png)

**Comment by echan-bridgephase** [comment]
Thanks for catching that Jaime. It looks fine now!
