### ISSUE TITLE
Header Title for each Page (i.e. 'Consider the following - Medicine')

### ISSUE THREAD

**Issue by echan-bridgephase** [BridgePhase/ctf#31]
The header should reflect the appropriate page that the user is on. For example, 'Consider the following - Medicine'. 
![considerthefollowing_titleforeachpage](https://cloud.githubusercontent.com/assets/13000338/8284192/a69d45f8-18c9-11e5-902e-c675c4c1f888.jpg)

**Comment by jgarciarbridgephase** [comment]
Yes, it should be

**Comment by jgarciarbridgephase** [comment]
Titles update correctly now in prod
![screen shot 2015-06-22 at 6 20 38 pm](https://cloud.githubusercontent.com/assets/12414982/8294593/766fcf76-190b-11e5-8741-9b4d9eac50c7.png)
