### ISSUE TITLE
Drilling into an event loads the page minus the header

### ISSUE THREAD

**Issue by belyea** [BridgePhase/ctf#38]
Not sure if this is by design or not, but when drilling into an event, the page reloads but moves the top of the page to be the sub section with no headers. Screenshot:

![with header before clicking](https://cloud.githubusercontent.com/assets/11012844/8298012/2b91405e-1931-11e5-8a14-9803647d74f6.JPG)

![no header after clicking](https://cloud.githubusercontent.com/assets/11012844/8298011/2b9054e6-1931-11e5-9f5a-8a9e23bd153f.JPG)

**Comment by jgarciarbridgephase** [comment]
It was kind of by design, especially when you're in a mobile environment it makes sure that the user gets taken to the that actually shows the information otherwise you wouldn't see it.

**Comment by belyea** [comment]
@jgarciarbridgephase  - got it. that makes sense then, will close this issue.
