### ISSUE TITLE
Is it possible to adjust column sizing on data table?

### ISSUE THREAD

**Issue by belyea** [BridgePhase/ctf#40]
Seems like we have a lot of white space for the "Recall started on" field that could be better served for use by the "Product Description" field. Can we adjust? See screenshot:

![column resizing](https://cloud.githubusercontent.com/assets/11012844/8298107/4ebb34f8-1932-11e5-9a67-ede3f9d3929b.JPG)

**Comment by jgarciarbridgephase** [comment]
I'm going to add jQuery DataTables to fix this

**Comment by jgarciarbridgephase** [comment]
Fixed by showing lists
![screen shot 2015-06-23 at 5 15 37 pm](https://cloud.githubusercontent.com/assets/12414982/8330102/f9b8682e-1a4c-11e5-8e7d-795abd0a2c16.png)
