### ISSUE TITLE
Pardon my ignorance - where is Palau???

### ISSUE THREAD

**Issue by belyea** [BridgePhase/ctf#41]
Although I really want to go there, I don't see anywhere on the interactive map where Palau shows up. Should we filter out any data that isn't a valid state / territory???

![where is palau](https://cloud.githubusercontent.com/assets/11012844/8298350/c0fd6af6-1935-11e5-9537-c0510707e69d.JPG)

**Comment by kgyovai** [comment]
Palau is a valid territory but you can't see it on the map since it's in the Pacific (https://en.wikipedia.org/wiki/File:Palau_on_the_globe_(Southeast_Asia_centered)_(small_islands_magnified).svg. I removed it from the list.
