### ISSUE TITLE
Is there a page 2? Only 100 of 185 displayed.

### ISSUE THREAD

**Issue by echan-bridgephase** [BridgePhase/ctf#42]
![100of185_page2](https://cloud.githubusercontent.com/assets/13000338/8313423/950684ca-19b0-11e5-97c2-c09a7ec3054d.jpg)

**Comment by jgarciarbridgephase** [comment]
yeah we're aware, we're going to change the wording but we're only going to display a max of 100 records.

**Comment by jgarciarbridgephase** [comment]
Replaced this with a list view, what do you think (I still need to sort them by date)?
![screen shot 2015-06-23 at 5 15 37 pm](https://cloud.githubusercontent.com/assets/12414982/8317430/819a804c-19cb-11e5-87c3-740a2d358573.png)

**Comment by jgarciarbridgephase** [comment]
Fixed by only displaying a max of 100 records

**Comment by echan-bridgephase** [comment]
There seems to be some spacing between the end of the table and the scroll bar. I'm using Firefox. Are you seeing this too?
![table_scrollbar_spacing](https://cloud.githubusercontent.com/assets/13000338/8330210/cb530e7a-1a4d-11e5-9dfb-a7c470ebe773.jpg)

**Comment by jgarciarbridgephase** [comment]
How about in other browsers? (it's probably b/c that scrollbar shows up :disappointed:

**Comment by echan-bridgephase** [comment]
Also-- is there a way to sort by category? I.e. Dairy, Frozen Items (?), Fruits and Vegetables, Canned Goods (?), Snacks (?), etc.

**Comment by jgarciarbridgephase** [comment]
We can sort by Class of recall, the FDA marks the categories into 3 types Class I, II, and III. I can display that and sort by class (I would also need to provide a legend explaining what these classes mean)

**Comment by echan-bridgephase** [comment]
The class of recall will be more informative to the users so they can view the severity of the food recalls. Good job Jaime!

**Comment by jgarciarbridgephase** [comment]
Hi @echan-bridgephase, this is now fixed.

I implemented a "Test" environment so that we can test issues before we move to production. So can you please test this on http://54.175.58.210:8080/ctf/

Thanks!

**Comment by echan-bridgephase** [comment]
Confirmed fix!  Thanks!
