### ISSUE TITLE
Recall Description Formatting

### ISSUE THREAD

**Issue by echan-bridgephase** [BridgePhase/ctf#45]
For each recall description and title, is it possible to indent details about each product or move them into a separate line? Here's a suggestion, but do whatever works best. 

![recall_description_format](https://cloud.githubusercontent.com/assets/13000338/8330360/d9dfd562-1a4e-11e5-940e-0207daa4002d.jpg)

**Comment by jgarciarbridgephase** [comment]
Yeah I know, unfortunately that's how we get data from the FDA. Some descriptions are longer than others and we don't want to hide the full description from the user. Not every description will contain the same information either.

**Comment by jgarciarbridgephase** [comment]
Ok I'm going to try something for food, I'll let you know how it works.

**Comment by jgarciarbridgephase** [comment]
How's this @echan-bridgephase ?
![screen shot 2015-06-24 at 3 04 12 pm](https://cloud.githubusercontent.com/assets/12414982/8338981/5a0cb588-1a82-11e5-82a3-49e921463242.png)

**Comment by echan-bridgephase** [comment]
This looks a lot cleaner. Do you have a screenshot of how it looks when there is no UPC? I'm curious how the one with no UPC will look like. :)

**Comment by jgarciarbridgephase** [comment]
@echan-bridgephase this is ready to be tested, yesterday I implemented a "Test" environment so that we can test issues before we move to production. So can you please test this on http://54.175.58.210:8080/ctf/

Thanks!

**Comment by echan-bridgephase** [comment]
This looks much better! Thanks Jaime!
