### ISSUE TITLE
Add description to the Bow Tie Icon

### ISSUE THREAD

**Issue by kelle2dm** [BridgePhase/ctf#46]
I like the icon, however I would put a caption/footer on the bottom of it so that users know that the functionality is to bring them back to the home page.

**Comment by jgarciarbridgephase** [comment]
we want to keep this one clean, most sites don't include that information since on 90%+ of sites, clicking on the logo always takes you to their homepage. Recommend closing.

**Comment by kelle2dm** [comment]
Okay that's fine, please close.

Sent from my iPhone

On Jun 26, 2015, at 7:35 PM, Jaime Garcia Ramirez <notifications@github.com<mailto:notifications@github.com>> wrote:


we want to keep this one clean, most sites don't include that information since on 90%+ of sites, clicking on the logo always takes you to their homepage. Recommend closing.
