### ISSUE TITLE
More descriptive subheading on the homepage

### ISSUE THREAD

**Issue by kelle2dm** [BridgePhase/ctf#48]
I would suggest adding a more descriptive language to the "Would you like to know more?" subheading to draw the users attention to the 3 categories. Perhaps something like, "Select an icon below to find out more." or "To find out more, select an icon below."

**Comment by jgarciarbridgephase** [comment]
@kelle2dm - does this work for you?

![screen shot 2015-06-26 at 9 22 53 pm](https://cloud.githubusercontent.com/assets/12414982/8389874/86438f50-1c49-11e5-9de9-29a63b295d53.png)

**Comment by kelle2dm** [comment]
Yes, I like that this is more descriptive. Close issue.
