### ISSUE TITLE
Change the white background on the homepage to make it less of a contrast

### ISSUE THREAD

**Issue by kelle2dm** [BridgePhase/ctf#51]
I would suggest changing the white background behind the three icons on the homepage to a tan or a color that isn't such a contrast to the dark heading above it.

**Comment by jgarciarbridgephase** [comment]
it's not really white anymore, it's a grayish color. Deferring to @echan-bridgephase and @belyea to see what they think.

**Comment by belyea** [comment]
I like the new color scheme!!!

**Comment by kelle2dm** [comment]
I like the new color scheme as well! Good to close
