### ISSUE TITLE
Enhance "What medicines are you taking?" heading

### ISSUE THREAD

**Issue by kelle2dm** [BridgePhase/ctf#52]
I would suggest changing the text of the "What medicines are you taking?" heading on the medication page to "What medicine are you looking for?".

**Comment by jgarciarbridgephase** [comment]
This is no longer a header, do we still that? here's the updated picture.

![screen shot 2015-06-26 at 7 19 52 pm](https://cloud.githubusercontent.com/assets/12414982/8389156/fffcfd1e-1c39-11e5-833d-0ba3d8fef3b0.png)

**Comment by kelle2dm** [comment]
Added in additional issue found in the bugbash, just change the subheading to "**medicines**" not medications to keep it consistent with the banner and the icon on the homepage.
