### ISSUE TITLE
Add transparent images behind all headers

### ISSUE THREAD

**Issue by kelle2dm** [BridgePhase/ctf#54]
I would suggest adding transparent images behind the heading on the homepage as well as the headings on the three sections. Perhaps make the images match the section type. (i.e. Food section, put a transparent image of apples behind the "Consider the following about food recalls" subheading, etc.)

**Comment by jgarciarbridgephase** [comment]
Help us find images :sunglasses:

**Comment by kelle2dm** [comment]
... I looked for an hour last night but no dice. I'm not giving  up yet though!
