### ISSUE TITLE
Suggestions for the medications page

### ISSUE THREAD

**Issue by kelle2dm** [BridgePhase/ctf#55]
Here are some suggestions on the medicines page:
**Option 1**: Have the ability to filter on two fields:
1. Name of the medication 
and/or
2. Class (Class 1, Class 2, Class 3, etc.)

**Option 2**: Have each letter of the alphabet present under the heading and allow the user to click on the letter of the medication they are looking for. Upon selecting a letter, say the user selected "A" for Advil, all the medications that have been recalled that begin with the letter "A" would appear in the search results. The user would then select their medication (Advil) and information on the medication would appear on the screen. 

**Note**-Whichever option we choose, I think it would be valuable to include a legend on what differentiates the classes and what classes are.

**Comment by jgarciarbridgephase** [comment]
So this screen has changed quite a bit, is this still applicable @kelle2dm ?

**Comment by jgarciarbridgephase** [comment]
@kelle2dm, any news?

**Comment by kelle2dm** [comment]
This was just suggested feedback prior to us having a design in mind for the medicines page. I would say to close this as it is not applicable anymore.

Sent from my iPhone

On Jun 29, 2015, at 7:59 PM, Jaime Garcia Ramirez <notifications@github.com<mailto:notifications@github.com>> wrote:


@kelle2dm<https://github.com/kelle2dm>, any news?
