### ISSUE TITLE
Suggestion for Food Recall Page

### ISSUE THREAD

**Issue by echan-bridgephase** [BridgePhase/ctf#58]
Is it possible to switch the 'Select a recall to view more details' and the 'Results' table? This may help with the blank space on the right. In addition, this may relieve the view of the website on a mobile phone (On a mobile phone, the 'Select a recall...' section is displayed below the 'Results' table.) 

Another suggestion is to make the 'Results table' smaller, so when one of the results is clicked, the details will display below it.

![switchtables_06252015](https://cloud.githubusercontent.com/assets/13000338/8356538/fbe0d5aa-1b23-11e5-836c-4f43b77e93c7.jpg)

**Comment by jgarciarbridgephase** [comment]
Referencing issue #39 , since it's basically covered here. Closing #39

**Comment by jgarciarbridgephase** [comment]
this has already been address, @echan-bridgephase, please confirm.

**Comment by echan-bridgephase** [comment]
Confirmed fix. :+1:
