### ISSUE TITLE
In Mobile view - Text is cut off for Consider the following...

### ISSUE THREAD

**Issue by echan-bridgephase** [BridgePhase/ctf#66]
Text is cut off. See screenshot. 

![image](https://cloud.githubusercontent.com/assets/13000338/8389853/8e881ce0-1c48-11e5-90a4-b6c1fae8476f.jpg)

**Comment by jgarciarbridgephase** [comment]
I knew you were going to point this one out. I had already noticed it, just haven't had a chance to fix it :smile:

**Comment by echan-bridgephase** [comment]
Hahaha. I do like that you updated the arrows. :)

**Comment by echan-bridgephase** [comment]
Looks good. Great job!
