### ISSUE TITLE
Bowtie doesn't return back to the homepage (except for the "Team Member" page)

### ISSUE THREAD

**Issue by belyea** [BridgePhase/ctf#69]
For majority of pages - i.e. http://considerbridgephase.com/ctf/#/noun/food - clicking on the bowtie does not return the user to the home page. It does work on the team member page.

**Comment by jgarciarbridgephase** [comment]
Tried this in IE 9, IE 10, Chrome, FF, no cigar :cry:

**Comment by jgarciarbridgephase** [comment]
This is now fixed, it was a problem with z-index. @belyea can you confirm on the staging environment?

**Comment by belyea** [comment]
Am I in the right staging environment? I don't see the fix:
http://bp-testdeployslb-1690116647.us-east-1.elb.amazonaws.com/ctf/#/noun/medicine

**Comment by belyea** [comment]
ok, I didn't see it in staging but I pulled and it worked great locally so I am going to close. Thanks!
