### ISSUE TITLE
Modify the notification caching strategy to more frequently rotate the <noun>

### ISSUE THREAD

**Issue by belyea** [BridgePhase/ctf#72]
Due to our caching strategy in prod, when I refresh, I always get the same value in the carousal. Is it possible to dynamically retrieve a new <noun> when refreshing? Also, should we reconsider our caching time (currently set to twice daily).

**Comment by jgarciarbridgephase** [comment]
@kgyovai, do as you will with this one, thanks

**Comment by kgyovai** [comment]
Just wrapped and pushed this one. The notifications look much more dynamic now. The data is still cached but a randomized subset of that data is returned upon request.

**Comment by belyea** [comment]
tested locally and its looking good, thanks! Closing.
