### ISSUE TITLE
Increase the time that each notification is displayed on the customer homepage

### ISSUE THREAD

**Issue by kelle2dm** [BridgePhase/ctf#73]
Increase the time that each notification is displayed on the customer homepage. Some of the longer notifications seem to rotate a little quick. @kgyovai

**Comment by jgarciarbridgephase** [comment]
This is now 7 seconds, @kelle2dm are you ok with that?

**Comment by kelle2dm** [comment]
Yes, looks good to me. Able to close issue now.
