### ISSUE TITLE
Header image for "home" and "aboutus" is the same but is sized differently across each

### ISSUE THREAD

**Issue by belyea** [BridgePhase/ctf#74]
would it be possible to resize to make the transition of the header consistent when navigating between these two specific pages

**Comment by jgarciarbridgephase** [comment]
@belyea - resizing this to a fixed size makes it appear odd on mobile.

**Comment by jgarciarbridgephase** [comment]
I recommend we keep this the same, let us know.

**Comment by belyea** [comment]
Works for me. I will close.
