### ISSUE TITLE
For Medical Devices page, the resultant data set displayed can be very duplicative

### ISSUE THREAD

**Issue by belyea** [BridgePhase/ctf#76]
For example, scrolling thorugh the list of 79 items returned, the following is displayed many times with no additional information:
SPRINT FIDELIS
MPRI

Is there any other identifying information returned in the dataset that we could display to differentiate a bit? For example, a date that it happened? Or a unique identifier assigned to the event?

**Comment by jgarciarbridgephase** [comment]
We don't really get a lot of data back for medical devices and most of the data doesn't seem very informative. I can see if I can add the date there

**Comment by belyea** [comment]
I see the date added, looks great, closing this issue.
