### ISSUE TITLE
Suggestion for Medications page - When no medication is entered, and the 'Search' button is clicked...

### ISSUE THREAD

**Issue by echan-bridgephase** [BridgePhase/ctf#80]
When no medication is entered, and the 'Search' button is clicked, the 'Adverse events reported in which the patient was taking...' line should not be displayed. Or displayed something along the lines of 'Enter Medication name to search for adverse events involving medications.' 
![bugbash_search_nomedication_entered](https://cloud.githubusercontent.com/assets/13000338/8415599/051770b4-1e6e-11e5-9342-dc6ac3e447a3.jpg)

**Comment by jgarciarbridgephase** [comment]
This is fixed now, confirm in the testing environment please @echan-bridgephase

**Comment by echan-bridgephase** [comment]
I would add:
- a period after 'name'. 
There are no search results for your query of medicines with: "" in the name. <-- Add period.
- update the comma after term to a period. Capitalize 'r' for remember. 
Try your search again with a different search term. Remember you can include different medicine names by separating them with commas.

Thanks!

**Comment by jgarciarbridgephase** [comment]
ok fixed again, deploying now

**Comment by echan-bridgephase** [comment]
Confirmed fix. Thanks for the quick turnaround! :+1:
