### ISSUE TITLE
On medicines page, do not supply a graph when no search results are present

### ISSUE THREAD

**Issue by kelle2dm** [BridgePhase/ctf#83]
On the medicines page, when a user enters a medicine in the search bar that does not have any results then the graph should not be displayed on the screen. This should be the case for both single searches as well as combination searches. I would suggest adding an error message notifying the user that "There are no adverse events associated to "display name that user entered"."

e.g. Single search: Exubera

e.g. Multi search: Ezetimibe and Atorvastatin Tablets, Tums, Midol

**Comment by jgarciarbridgephase** [comment]
This is already addressed with #80, closing this one
