### ISSUE TITLE
Sorting of recall data returned

### ISSUE THREAD

**Issue by belyea** [BridgePhase/ctf#84]
Looks like the list is trying to sort on date, but its not consistent. See image:
![sort order](https://cloud.githubusercontent.com/assets/11012844/8415869/b7b81dbc-1e6f-11e5-8d19-6db3dea10b57.JPG)

**Comment by kgyovai** [comment]
The initial implementation of the sort was done to show the most serious recalls first then sort by date after that. Now the sort is first done by date and then by recall classification. The newest, most serious recalls will be on top.

**Comment by belyea** [comment]
Oh ok, I hadn't paid attention to the Class I vs. Class II classification. Makes sense now :-)  This looks good as well, closing.
