### ISSUE TITLE
On the food recall page, are the states still supposed to auto-populate?  If so, it's not working on my computer..

### ISSUE THREAD

**Issue by belyea** [BridgePhase/ctf#86]
See image:
![statesautoload](https://cloud.githubusercontent.com/assets/11012844/8415911/046eb616-1e70-11e5-8fd0-7de7e867eb0a.JPG)

IE 10.0.92000.17377

**Comment by jgarciarbridgephase** [comment]
Looks like an IE issue... IE9??

**Comment by jgarciarbridgephase** [comment]
You should try this again, I wasn't able to replicate it.

**Comment by belyea** [comment]
Yeah, working for me to. Defaulted to DC at the office and now defaulting to Virginia at home. Pretty cool. Wonder if Matt's ISP block's his location? Regardless, I think it is working fine, closing.
