### ISSUE TITLE
Medical Devices page - Is there a need for 'Type of event'?

### ISSUE THREAD

**Issue by echan-bridgephase** [BridgePhase/ctf#90]
Is the 'Type of event' necessary since this page only displays 'Deaths resulting in device recalls over the last year'?

Instead of 'last year', can we put a specific date range? 'Deaths resulting in device recalls since 2014'?

![bugbash_medicaldevices_page](https://cloud.githubusercontent.com/assets/13000338/8416126/896f2566-1e71-11e5-98ba-81f90ce1c171.jpg)

**Comment by jgarciarbridgephase** [comment]
I can give you "over the past year". Not since 2014. For the other pages we don't specify exact dates (except for the food recalls). Even on that page we say "in the past XX months" or something like that.

**Comment by echan-bridgephase** [comment]
Confirmed fix.

Also liked that you updated to 'Date of Event' instead of 'Type of Event'.
